# Generated by Django 3.0.7 on 2020-06-23 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_perfil', models.CharField(max_length=255)),
                ('descripcion_tipo_perfil', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='images/perfil/')),
                ('fecha_nacimiento', models.DateField(blank=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono_fijo', models.CharField(blank=True, max_length=20)),
                ('telefono_movil', models.CharField(blank=True, max_length=20)),
                ('tipo_perfil', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='perfil.Tipo_Perfil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
