# Generated by Django 3.0.7 on 2020-06-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_auto_20200623_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='rut',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
