# Generated by Django 3.0.7 on 2020-06-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0005_auto_20200620_2353'),
        ('voluntario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades_Voluntario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Casa_Temporal',
        ),
        migrations.CreateModel(
            name='Casa_Temporal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('adoption.tipo_pet',),
        ),
        migrations.AddField(
            model_name='actividades_voluntario',
            name='casa_temporal',
            field=models.ManyToManyField(to='voluntario.Casa_Temporal'),
        ),
    ]
