# Generated by Django 3.0.7 on 2020-06-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0001_initial'),
        ('voluntario', '0002_auto_20200623_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades_voluntario',
            name='donaciones',
            field=models.ManyToManyField(blank=True, to='donacion.Tipo_Donacion'),
        ),
        migrations.AlterField(
            model_name='actividades_voluntario',
            name='casa_temporal',
            field=models.ManyToManyField(blank=True, to='voluntario.Casa_Temporal'),
        ),
    ]
