# Generated by Django 3.0.7 on 2020-06-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
        ('voluntario', '0003_auto_20200623_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades_voluntario',
            name='eventos',
            field=models.ManyToManyField(blank=True, to='evento.Tipo_Evento'),
        ),
    ]
