# Generated by Django 3.0.7 on 2020-06-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntario', '0004_actividades_voluntario_eventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades_voluntario',
            name='capacitacion',
            field=models.BooleanField(default=False, verbose_name='Capacitaciones, Charlas'),
        ),
        migrations.AddField(
            model_name='actividades_voluntario',
            name='cuidados_veterinarios',
            field=models.BooleanField(default=False, verbose_name='Cuidados Veterinarios'),
        ),
        migrations.AddField(
            model_name='actividades_voluntario',
            name='experiencia',
            field=models.TextField(blank=True, verbose_name='Experiencia'),
        ),
        migrations.AddField(
            model_name='actividades_voluntario',
            name='extra',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='actividades_voluntario',
            name='legal',
            field=models.BooleanField(default=False, verbose_name='Legal(escritos, trámites, denuncias)'),
        ),
        migrations.AddField(
            model_name='actividades_voluntario',
            name='representacion_medios',
            field=models.BooleanField(default=False, verbose_name='Representación Medios'),
        ),
        migrations.AddField(
            model_name='actividades_voluntario',
            name='rescates',
            field=models.BooleanField(default=False, verbose_name='Rescates'),
        ),
        migrations.AddField(
            model_name='actividades_voluntario',
            name='vehiculo',
            field=models.BooleanField(default=False, verbose_name='Vehículo'),
        ),
    ]
