# Generated by Django 3.0.7 on 2020-06-23 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_auto_20200623_1829'),
        ('voluntario', '0005_auto_20200623_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades_voluntario',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.Perfil'),
        ),
    ]
