# Generated by Django 3.0.7 on 2020-06-30 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_contacto'),
        ('voluntario', '0006_actividades_voluntario_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otras_actividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actividad', models.CharField(max_length=255)),
                ('descripcion_actividad', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='actividades_voluntario',
            name='capacitacion',
        ),
        migrations.RemoveField(
            model_name='actividades_voluntario',
            name='cuidados_veterinarios',
        ),
        migrations.RemoveField(
            model_name='actividades_voluntario',
            name='legal',
        ),
        migrations.RemoveField(
            model_name='actividades_voluntario',
            name='representacion_medios',
        ),
        migrations.RemoveField(
            model_name='actividades_voluntario',
            name='rescates',
        ),
        migrations.RemoveField(
            model_name='actividades_voluntario',
            name='vehiculo',
        ),
        migrations.CreateModel(
            name='Solicitud_Voluntario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('actividades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voluntario.Actividades_Voluntario')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.Perfil')),
            ],
        ),
        migrations.AddField(
            model_name='actividades_voluntario',
            name='otras_actividades',
            field=models.ManyToManyField(blank=True, to='voluntario.Otras_actividades'),
        ),
    ]
