# Generated by Django 3.0.7 on 2020-06-18 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Adopcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Esterilizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esterilizado', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tamano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamano', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pet', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Mascota')),
                ('edad', models.IntegerField(help_text='Meses')),
                ('historia', models.TextField()),
                ('imagen_destacada', models.ImageField(upload_to='fotos/pet/')),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='fotos/pet/')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='fotos/pet/')),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoption.Color')),
                ('estado_adopcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoption.Estado_Adopcion')),
                ('esterilizado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoption.Esterilizado')),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoption.Raza')),
                ('tamano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoption.Tamano')),
                ('tipo_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoption.Tipo_Pet')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoption.Ubicacion')),
            ],
        ),
    ]
