# Generated by Django 3.0.7 on 2020-06-18 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='sexo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adoption.Sexo'),
        ),
    ]
