# Generated by Django 3.0.7 on 2020-06-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_pet_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esterilizado',
            name='esterilizado',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='pet',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='images/adoption/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='images/adoption/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='imagen_destacada',
            field=models.ImageField(upload_to='images/adoption/'),
        ),
    ]
