# Generated by Django 3.0.7 on 2020-06-20 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0003_auto_20200620_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuidados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cuidado', models.CharField(max_length=255)),
                ('descripcion_cuidado', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Desparasitado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desparasitado', models.CharField(max_length=50)),
                ('fecha_desparasitado', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Salud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_salud', models.CharField(max_length=100)),
                ('fecha_chequeo', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacuna', models.CharField(max_length=50)),
                ('fecha_vacuna', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='chip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='estado_adopcion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adoption.Estado_Adopcion'),
        ),
        migrations.AddField(
            model_name='pet',
            name='cuidados_especiales',
            field=models.ForeignKey(null=True, on_delete=models.Model, to='adoption.Cuidados'),
        ),
        migrations.AddField(
            model_name='pet',
            name='desparasitado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adoption.Desparasitado'),
        ),
        migrations.AddField(
            model_name='pet',
            name='estado_salud',
            field=models.ForeignKey(null=True, on_delete=models.Model, to='adoption.Salud'),
        ),
        migrations.AddField(
            model_name='pet',
            name='vacunado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adoption.Vacuna'),
        ),
    ]
