# Generated by Django 3.0.7 on 2020-06-20 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0004_auto_20200620_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desparasitado',
            name='fecha_desparasitado',
        ),
        migrations.RemoveField(
            model_name='salud',
            name='fecha_chequeo',
        ),
        migrations.RemoveField(
            model_name='vacuna',
            name='fecha_vacuna',
        ),
    ]
