# Generated by Django 3.0.7 on 2020-06-29 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_perfil_rut'),
        ('adoption', '0005_auto_20200620_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud_Adopcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now=True)),
                ('estado_solicitud', models.BooleanField()),
                ('comentarios_solicitud', models.TextField(blank=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.Perfil')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoption.Pet')),
            ],
        ),
    ]
