# Generated by Django 3.0.7 on 2020-06-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0006_solicitud_adopcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_adopcion',
            name='estado_solicitud',
            field=models.BooleanField(blank=True),
        ),
    ]
