# Generated by Django 3.0.7 on 2020-06-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0007_auto_20200629_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_adopcion',
            name='estado_solicitud',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
