# Generated by Django 3.0.7 on 2020-06-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0008_auto_20200629_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_adopcion',
            name='fecha_solicitud',
            field=models.DateField(auto_now_add=True),
        ),
    ]
